docs: add Mac M1 build conan
symbol/catapult-client pull request #182
Opened 2021-07-14 20:42 UTC by AnthonyLaw

2021-07-15 07:39 UTC, segfaultxavi requested changes
I prefer to keep machine-specific instructions to a minimum, otherwise, this will explode in the future...

2021-07-15 07:39 UTC, segfaultxavi commented on docs/BUILD-conan.md
> +      ```
For simplicity, I would merge this new section with the previous one:
- Add `pkg-config` to the `brew install` line (it does not hurt to always install it, right?)
- Add step 4 as it is, with a note:
  ```
  4. Set the right config for Conan (Only for Mac M1):
  ```

2021-07-15 07:39 UTC, segfaultxavi commented on docs/BUILD-conan.md
> +
I would turn this note into step 5 in the above list:
```
5. Modify `conanfile.txt` (Only for Mac M1):
```

2021-07-15 07:39 UTC, segfaultxavi commented on docs/BUILD-conan.md
> +cd catapult-client
This should go to a different commit, it's unrelated to the M1 instructions.

2021-07-19 07:21 UTC, AnthonyLaw commented
> I prefer to keep machine-specific instructions to a minimum, otherwise, this will explode in the future...

Agree, i made some change for that ;)

2021-07-26 06:09 UTC, segfaultxavi approved these changes
Sorry for the late review, I was on holiday!

2021-08-06 14:14 UTC, Jaguar0625 commented on docs/BUILD-conan.md
> +  4. Set the right config for Conan (Only for Mac M1):
can you please remove `(Only for Mac M1)` from 4?

2021-08-06 15:18 UTC, segfaultxavi approved these changes

2021-08-06 15:27 UTC, Jaguar0625 commented
Merged in d4e11e01bceefa1ffcf854f34f168b00e42127e2.

2021-08-06 15:27 UTC, closed without merging