docs: rename catapult-server to catapult-client in docs
symbol/catapult-client pull request #189
Opened 2021-08-04 13:41 UTC by Jaguar0625

2021-08-04 15:29 UTC, Wayonb requested changes

2021-08-05 08:13 UTC, segfaultxavi requested changes
There are more broken links but I will submit another patch for them as they are unrelated to this changeset.

2021-08-05 08:13 UTC, segfaultxavi commented on README.md
>  [![docs](badges/docs--green.svg)](https://nemtech.github.io)
```suggestion
[![docs](badges/docs--green.svg)](https://symbol.github.io)
```

2021-08-05 08:13 UTC, segfaultxavi commented on README.md
>  Learn more about the protocol by reading the [whitepaper] and the  [developer documentation].
```suggestion
Learn more about the protocol by reading the [technical reference] and the  [developer documentation].
```

2021-08-05 08:13 UTC, segfaultxavi commented on README.md
>  | /external | External dependencies that are built with the server. |
```suggestion
| /external | External dependencies that are built with the client. |
```

2021-08-05 08:13 UTC, segfaultxavi commented on README.md
>  [whitepaper]: https://nemtech.github.io/catapult-whitepaper/main.pdf
```suggestion
[technical reference]: https://symbol.github.io/symbol-technicalref/main.pdf
```

2021-08-05 08:13 UTC, segfaultxavi commented on docs/RUNPEERLIN.md
> +These instructions summarize the minimum number of steps to run a [peer node](https://nemtech.github.io/concepts/node.html#id1) and connect it to an existing network using the catapult-client build.
```suggestion
These instructions summarize the minimum number of steps to run a [peer node](https://symbol.github.io/concepts/node.html#id1) and connect it to an existing network using the catapult-client build.
```

2021-08-05 14:41 UTC, gimer approved these changes

2021-08-05 14:42 UTC, segfaultxavi approved these changes

2021-08-05 14:45 UTC, Wayonb approved these changes

2021-08-05 14:47 UTC, merged