Made changes to support linter for the cpp sdk
symbol/catapult-client pull request #193
Opened 2021-08-17 11:29 UTC by Momo10101

I have made the least amount of changes necessary to add linter support for c++ sdk. The rest of the changes have been done in the sdk. Linter script will work as is on sdk by using the 'exclusions.py' in the sdk repo. The linter should probably be moved to its own project once PR has been accepted.

2021-08-17 12:34 UTC, gimre-xymcity approved these changes

2021-08-19 14:54 UTC, Jaguar0625 requested changes
please run python linters (lint.sh file)

2021-08-19 14:54 UTC, Jaguar0625 commented on scripts/lint/Rules.py
> +            if 'int' in path_elements or 'bench' in path_elements or 'stress' in path_elements:
```python
if any(subdir in path_elements for subdir in ['int', 'bench', 'stress']):
```

2021-08-20 14:16 UTC, Jaguar0625 approved these changes

2021-08-20 14:18 UTC, Jaguar0625 commented
Merged in 5dbdcb27.

2021-08-20 14:18 UTC, closed without merging